#' Shortcut to 'descriptives.scan'
#' 
#' Shortcut to 'descriptives.scan'
#' 
#' @param object object of class 'scan.gwaa' as generated by 
#' \code{\link{qtscore}}, \code{\link{mlreg}}, etc.
#' 
#' @param ... arguments passed to \code{\link{descriptives.scan}}
#' 
#' @examples 
#' data(srdta)
#' x <- qtscore(qt2,srdta)
#' summary(x)
#' 
#' @author Yurii Aulchenko
#' 
"summary.scan.gwaa" <- 
		function(object,...) {
	ret <- descriptives.scan(object, ... )
	ret
}
